### ISSUE TITLE
Overview: Implement ETL scripts for blocks, transactions, and actions

### ISSUE THREAD

**Issue by medvedev1088** [blockchain-etl/eos-etl#1]
The scope of this task is:

1. Implement a job for exporting blocks, transactions and actions using [export_blocks_and_transactions.py ](https://github.com/blockchain-etl/bitcoin-etl#export_blocks_and_transactions) as a basis. Result should be in 3 CSV files: `blocks.csv`, `transactions.csv`, `actions.csv`.
1. Implement tests using [test_export_blocks_job.py](https://github.com/blockchain-etl/bitcoin-etl/blob/master/tests/bitcoinetl/job/test_export_blocks_job.py) as a basis.
1. Implement get_block_range_for_date using [get_block_range_for_date](https://github.com/blockchain-etl/bitcoin-etl#get_block_range_for_date) as a basis.
_**Optional**_
1. Implement [Dockerfile](https://github.com/blockchain-etl/ethereum-etl#running-in-docker)
1. Write documentation in README using [Exporting the Blockchain](https://github.com/blockchain-etl/ethereum-etl#exporting-the-blockchain) as a basis.
1. Test the scripts on a bigger range of blocks (5 days) on latest data to make sure the script don't fail.

**Notes/questions:**
1. There are a few EOS clients in Python to choose from https://github.com/Netherdrake/awesome-eos#python. The simplest one with minimal dependencies is preferable.
1. Does EOS api allow batching requests into a single HTTP payload?
1. Does this api https://developers.eos.io/eosio-nodeos/reference#get_block return full transactions or only hashes?
1. Are block timestamps in EOS monotonic? If yes get_block_range_for_date can be optimized. Read this for reference https://twitter.com/EvgeMedvedev/status/1073844856009576448. 
1. Reuse blockchainetl package from bitcoin-etl https://github.com/blockchain-etl/bitcoin-etl/tree/master/blockchainetl. Don't worry about copy-pasting the code for now. This package will be moved to a separate repo later and included as a dependency.
1. Read this article to understand the overall architecture https://cloud.google.com/blog/products/data-analytics/ethereum-bigquery-how-we-built-dataset.

**Comment by aelbuni** [comment]
@medvedev1088 I am currently reading through the plan and previous ETL jobs written for other blockchain networks.

Quick question: For testing, what kind of testing has been done before? Is it something in a form of smoke testing for the API interface the script is using to check that validity of the script?

**Comment by medvedev1088** [comment]
@aelbuni I'm using pytest to run unit and integration tests https://github.com/blockchain-etl/bitcoin-etl#running-tests. 

If you run `pytest -vv` in bitcoin-etl it will run tests against mock data. Here is an example of such data https://github.com/blockchain-etl/bitcoin-etl/tree/master/tests/resources/test_export_blocks_job/bitcoin/block_1. 

If before running the tests you specify provider uri e.g. 

```
export BITCOINETL_BITCOIN_PROVIDER_URI=http://user:pass@localhost:8332
pytest -vv
```
it will also run the same tests against the actual node.

**Comment by medvedev1088** [comment]
@aelbuni Hi. How is the progress? Do you have any questions or need any help?
