### ISSUE TITLE
Agree on JSON format

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [blockchain-etl/eos-etl#2]
Check attached files and make comments if you have any issues with it. 
If it is ok - please say it in comments.
[export json files](https://github.com/blockchain-etl/eos-etl/files/3123862/out.zip)

**Comment by medvedev1088** [comment]
If you already have mapper files or any file with the list of exported fields (e.g. a README section like this one https://github.com/blockchain-etl/ethereum-etl#transactionscsv), please create a PR with those. 

Meanwhile:

1. Are the `trx.` and `trx.transaction.` prefixes necessary in the transactions.json?
2. Is the `status` field mutable in the transactions.json file? If it's mutable don't include in the output. Any other mutable fields should be excluded also.
3. `trx.transaction.actions` seems redundant in transactions.json as actions are in actions.json. (Separating actions from transactions will make a difference for streaming, as there is a limit of 1MB for a single record in BigQuery. When loading from files though the limit is 100MB per record)
4. Is it possible to split the `quantity` field into a numeric value and a unit? This way people won't need to parse it in BigQuery. Are there any restrictions on the numeric values in EOS? E.g. how many bytes are numeric values? Are they stored as floating points or as decimals? This will make a difference when choosing the data types in BigQuery. If there are no guarantees on this it might be safest to keep them as strings as they are now.

**Comment by Vasiliy-Bondarenko** [comment]
@medvedev1088 
1. not necessary, it's just a way it is in the structure of transaction in EOS. so this path is familiar to EOS devs. that's why i left it. do you think it's really worth changing?..
2. ok
3. ok
4. quantity is inside action which i do not parse at all because it has arbitrary format. so parsing it will work only on small subset of actions. like eosio.token transfers. but we can have other actions with quantities as well. and other tokens. so it's a separate task to parse actions.
